[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MatiasMaravi/D3Bridge/blob/main/examples/dataset.ipynb)

# **Datasets**

This module aims to simulate the datasets used in D3.js. To do this, it's important to understand that JavaScript interprets a dataset as a list of **objects**.

To simulate this, we need a list of dictionaries.

In [1]:
import D3Bridge.datasets as ds

ds.list_available()

['alphabet',
 'sales',
 'state-population-2010-2019',
 'affairs',
 'iris',
 'gas',
 'Brazil',
 'USA',
 'sample']

In [2]:
df_alphabet = ds.get_dataset("alphabet") #List
df_alphabet

In [3]:
df_alphabet.columns

['letter', 'frequency']

Just as the library has some default test datasets, the user can also import their own datasets by specifying a path.

In [4]:
# Importing a dataset from a URL
df_navegadores = ds.read_dataset(r"https://gist.githubusercontent.com/MatiasMaravi/5e540b21eb04ca980d77199317e56ebb/raw/Explorers.tsv",sep="\t")
df_navegadores.head()

  explorer  frequency
0   Chrome      0.635
1   Safari      0.198
2     Edge      0.054
3  Firefox      0.028
4  Samsung      0.023

In [5]:
# Importing a dataset from a local file
df_local = ds.read_dataset(r"C:\Users\USUARIO\Desktop\VIZPRO-D3\D3Bridge\datasets\sales.csv")
df_local.head()

           market          segment  value
0      Auburn, AL    Almond lovers   3840
1      Auburn, AL     Berry buyers   1920
2      Auburn, AL   Carrots-n-more    960
3      Auburn, AL  Delicious-n-new    400
4  Birmingham, AL    Almond lovers   1600

It's important to note that the `get_dataset` and `read_dataset` functions return a custom class called `DataFrame`. This class itself isn't intended to replace how lists work. That's why there's an attribute called `data`. This attribute contains a list of dictionaries that simulate JavaScript objects.

In [6]:
df_local.data # We need to pass this attribute to our custom graphs.

[{'market': 'Auburn, AL', 'segment': 'Almond lovers', 'value': 3840},
 {'market': 'Auburn, AL', 'segment': 'Berry buyers', 'value': 1920},
 {'market': 'Auburn, AL', 'segment': 'Carrots-n-more', 'value': 960},
 {'market': 'Auburn, AL', 'segment': 'Delicious-n-new', 'value': 400},
 {'market': 'Birmingham, AL', 'segment': 'Almond lovers', 'value': 1600},
 {'market': 'Birmingham, AL', 'segment': 'Berry buyers', 'value': 1440},
 {'market': 'Birmingham, AL', 'segment': 'Carrots-n-more', 'value': 960},
 {'market': 'Birmingham, AL', 'segment': 'Delicious-n-new', 'value': 400},
 {'market': 'Gainesville, FL', 'segment': 'Almond lovers', 'value': 640},
 {'market': 'Gainesville, FL', 'segment': 'Berry buyers', 'value': 960},
 {'market': 'Gainesville, FL', 'segment': 'Carrots-n-more', 'value': 640},
 {'market': 'Gainesville, FL', 'segment': 'Delicious-n-new', 'value': 400},
 {'market': 'Durham, NC', 'segment': 'Almond lovers', 'value': 320},
 {'market': 'Durham, NC', 'segment': 'Berry buyers', 'value': 480},
 {'market': 'Durham, NC', 'segment': 'Carrots-n-more', 'value': 640},
 {'market': 'Durham, NC', 'segment': 'Delicious-n-new', 'value': 400}]

In [ ]:
df_local.min("value") #Value is the name of the column we want to get the minimum value from.

320

In [ ]:
df_local.max("value")#Value is the name of the column we want to get the maximum value from.

3840

In [7]:
df_local["value"] #Get all values ​​from the 'value' column as a list

[3840,
 1920,
 960,
 400,
 1600,
 1440,
 960,
 400,
 640,
 960,
 640,
 400,
 320,
 480,
 640,
 400]

In [8]:
df_local[0] # Get the first row of the dataset as a dictionary. The keys of the dictionary are the column names and the values are the corresponding values for that row.

{'market': 'Auburn, AL', 'segment': 'Almond lovers', 'value': 3840}

In [9]:
df_pandas = df_local._data #Accessing the underlying pandas DataFrame of our dataset.
df_pandas.head() #Show the first rows of the pandas DataFrame

           market          segment  value
0      Auburn, AL    Almond lovers   3840
1      Auburn, AL     Berry buyers   1920
2      Auburn, AL   Carrots-n-more    960
3      Auburn, AL  Delicious-n-new    400
4  Birmingham, AL    Almond lovers   1600