# Clase **Dataset** de la librería VizPro

Esta clase busca simular los datasets utilizados en D3.js. Para ello es oportuno entender que para javascript entiende un dataset como una lista de **Objetos**.

Para poder simular esto buscamos tener una lista de diccionarios.

In [1]:
import vizpro.datasets as Datasets

Datasets.list_available()

['alphabet', 'sales', 'state-population-2010-2019', 'affairs']

In [2]:
df_alphabet = Datasets.get_dataset("alphabet") #List
df_alphabet

In [3]:
df_alphabet.columns

['letter', 'frequency']

In [4]:
df_alphabet

Así como la libreria tiene por defecto algunos datasets de prueba, el usuario también puede importar sus propios datasets especificando una ruta.

In [5]:
# Importar un dataset desde una URL completa
df_navegadores = Datasets.read_dataset(r"https://gist.githubusercontent.com/MatiasMaravi/5e540b21eb04ca980d77199317e56ebb/raw/Explorers.tsv",sep="\t")
df_navegadores.head()

  explorer  frequency
0   Chrome      0.635
1   Safari      0.198
2     Edge      0.054
3  Firefox      0.028
4  Samsung      0.023

In [6]:
# Importar un dataset desde una ruta local
df_local = Datasets.read_dataset(r"C:\Users\USUARIO\Desktop\vizpro-D3\vizpro\datasets\sales.csv")
df_local.head()

           market          segment  value
0      Auburn, AL    Almond lovers   3840
1      Auburn, AL     Berry buyers   1920
2      Auburn, AL   Carrots-n-more    960
3      Auburn, AL  Delicious-n-new    400
4  Birmingham, AL    Almond lovers   1600

Es necesario detallar que la clase "Datasets" retorna una clase propia llamada "DataFrame". Esta clase en si no busca sustituir como funcionan las listas. Es por ello que hay un atributo llamado "data". Este atributo contiene una lista de diccionarios que simulan los objetos de javascript.

In [7]:
df_local.data # Necesitamos pasar este atributo a nuestros graficos personalizados.

[{'market': 'Auburn, AL', 'segment': 'Almond lovers', 'value': 3840},
 {'market': 'Auburn, AL', 'segment': 'Berry buyers', 'value': 1920},
 {'market': 'Auburn, AL', 'segment': 'Carrots-n-more', 'value': 960},
 {'market': 'Auburn, AL', 'segment': 'Delicious-n-new', 'value': 400},
 {'market': 'Birmingham, AL', 'segment': 'Almond lovers', 'value': 1600},
 {'market': 'Birmingham, AL', 'segment': 'Berry buyers', 'value': 1440},
 {'market': 'Birmingham, AL', 'segment': 'Carrots-n-more', 'value': 960},
 {'market': 'Birmingham, AL', 'segment': 'Delicious-n-new', 'value': 400},
 {'market': 'Gainesville, FL', 'segment': 'Almond lovers', 'value': 640},
 {'market': 'Gainesville, FL', 'segment': 'Berry buyers', 'value': 960},
 {'market': 'Gainesville, FL', 'segment': 'Carrots-n-more', 'value': 640},
 {'market': 'Gainesville, FL', 'segment': 'Delicious-n-new', 'value': 400},
 {'market': 'Durham, NC', 'segment': 'Almond lovers', 'value': 320},
 {'market': 'Durham, NC', 'segment': 'Berry buyers', 'value': 480},
 {'market': 'Durham, NC', 'segment': 'Carrots-n-more', 'value': 640},
 {'market': 'Durham, NC', 'segment': 'Delicious-n-new', 'value': 400}]

In [8]:
df_local.min("value") #Value es el nombre de la columna

320

In [9]:
df_local.max("value")#Value es el nombre de la columna

3840

In [10]:
df_local["value"] #Obtener todos los valores de la columna 'value' como una lista

[3840,
 1920,
 960,
 400,
 1600,
 1440,
 960,
 400,
 640,
 960,
 640,
 400,
 320,
 480,
 640,
 400]

In [12]:
df_local[0] # Obtener la primera fila como un diccionario

{'market': 'Auburn, AL', 'segment': 'Almond lovers', 'value': 3840}